/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _FILE_TRANSFER_H_RPCGEN
#define _FILE_TRANSFER_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct filechunk {
	char *filename;
	struct {
		u_int data_len;
		char *data_val;
	} data;
};
typedef struct filechunk filechunk;

struct transferstatus {
	bool_t success;
	char *message;
};
typedef struct transferstatus transferstatus;

#define FILE_TRANSFER_PROG 0x20000099
#define FILE_TRANSFER_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define SENDFILE 1
extern  transferstatus * sendfile_1(filechunk *, CLIENT *);
extern  transferstatus * sendfile_1_svc(filechunk *, struct svc_req *);
extern int file_transfer_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SENDFILE 1
extern  transferstatus * sendfile_1();
extern  transferstatus * sendfile_1_svc();
extern int file_transfer_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_filechunk (XDR *, filechunk*);
extern  bool_t xdr_transferstatus (XDR *, transferstatus*);

#else /* K&R C */
extern bool_t xdr_filechunk ();
extern bool_t xdr_transferstatus ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_FILE_TRANSFER_H_RPCGEN */
